version: '3'
services:
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    ports:
      - "8000:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress

  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf

  ftp:
    image: fauria/vsftpd
    ports:
      - "20:20"
      - "21:21"
    volumes:
      - ./ftp:/home/vsftpd
    environment:
      - FTP_USER=ftpuser
      - FTP_PASS=ftppassword
      - PASV_ADDRESS=127.0.0.1

  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot:/etc/letsencrypt
    command: certonly --webroot --webroot-path=/var/www/html --email your-email@example.com --agree-tos --no-eff-email -d your-domain.com

  ssh:
    image: linuxserver/openssh-server
    ports:
      - "2223:23"
    volumes:
      - ./ssh:/config
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London

  dns:
    image: sameersbn/bind:latest
    volumes:
      - ./named:/data/named
      - ./etc/named.conf:/etc/bind/named.conf:ro
    ports:
      - "54:54/udp"
      - "10000:10000/tcp"

  postfix:
    image: namshi/smtp
    ports:
      - "25:25"
    environment:
      - HOSTNAME=your-hostname
      - SMTP_USERNAME=your-smtp-username
      - SMTP_PASSWORD=your-smtp-password
      - RELAY_NETWORKS=your-network-range

volumes:
  db_data:
